### ISSUE TITLE
owl:inverseOf not materialized.

### ISSUE THREAD

**Issue by lu-pl** [gtfierro/reasonable#22] opened 2023-06-12 07:18 UTC
Sorry to bother you again, but I just did a very basic test and realized that `reasonable` apparently doesn't materialize `owl:inverseOf` inferences.

OS: Arch Linux
Python: 3.11
reasonable: 0.2.2

```python
import reasonable

from rdflib import Namespace, Graph

ex = Namespace("http://example.org/")

graph = Graph()
graph.add((ex.subj, ex.pred, ex.obj))
graph.add((ex.inverse, OWL.inverseOf, ex.pred))

r = reasonable.PyReasoner()
r.from_graph(graph)
entailed = r.reason()

print((ex.obj, ex.inverse, ex.subj) in entailed)   # False
```

Am I missing something or is this a problem with `reasonable`?

**Comment by gtfierro** [comment] 2023-06-13 03:49
Looks like it is a bug in `reasonable`! Suprised we didn't run into that sooner. I've pushed a fix to `reasonable==0.2.3` -- this should have the expected behavior.

**Closed by gtfierro** 2023-06-13 03:49 UTC
